@isTest
public class faultPartnerSoapSforceCom1Test {
    static testMethod void m1() {
    
    faultPartnerSoapSforceCom1.InvalidFieldFault obj1 = new faultPartnerSoapSforceCom1.InvalidFieldFault();
    
     faultPartnerSoapSforceCom1.InvalidSObjectFault  obj2 = new faultPartnerSoapSforceCom1.InvalidSObjectFault ();
     
      faultPartnerSoapSforceCom1.InvalidNewPasswordFault  obj3 = new faultPartnerSoapSforceCom1.InvalidNewPasswordFault ();
      
       faultPartnerSoapSforceCom1.ApiFault  obj4 = new faultPartnerSoapSforceCom1.ApiFault ();
       
        faultPartnerSoapSforceCom1.MalformedSearchFault  obj5 = new faultPartnerSoapSforceCom1.MalformedSearchFault ();
        
         faultPartnerSoapSforceCom1.LoginFault  obj6 = new faultPartnerSoapSforceCom1.LoginFault ();
         
          faultPartnerSoapSforceCom1.ApiQueryFault obj7 = new faultPartnerSoapSforceCom1.ApiQueryFault();
          
           faultPartnerSoapSforceCom1.InvalidQueryLocatorFault  obj8 = new faultPartnerSoapSforceCom1.InvalidQueryLocatorFault ();
           
            faultPartnerSoapSforceCom1.UnexpectedErrorFault  obj9 = new faultPartnerSoapSforceCom1.UnexpectedErrorFault ();
            
             faultPartnerSoapSforceCom1.InvalidIdFault  obj10 = new faultPartnerSoapSforceCom1.InvalidIdFault ();
             
             faultPartnerSoapSforceCom1.MalformedQueryFault   obj11 = new faultPartnerSoapSforceCom1.MalformedQueryFault  ();
            
    
    }
    }