@isTest
public class ReplicateTokenJsonTest{
    @isTest
    public static void testRepToken() {
        ReplicateTokenJson replicateTokenJson=new ReplicateTokenJson();
        ReplicateTokenJson.ReplicateToken replicateToken=new ReplicateTokenJson.ReplicateToken(); 
        ReplicateTokenJson.Sfdc sfdc=new ReplicateTokenJson.Sfdc();
        ReplicateTokenJson.Information info=new ReplicateTokenJson.Information(); 
        ReplicateTokenJson.Credit_Card_Details cardDetails=new ReplicateTokenJson.Credit_Card_Details();
        ReplicateTokenJson.Bank_Details bankDetails=new ReplicateTokenJson.Bank_Details(); 
        ReplicateTokenJson.Address address=new ReplicateTokenJson.Address();
    }
}