@isTest 
public class TENFORTYPREPTest
  {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='CCH1040PREPCERT_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
            //ATX Additional Users
            PageReference pageRef206 = Page.TenForty_Prep_Cert;
            
            Test.setCurrentPage(pageRef206);
            ApexPages.StandardController sc206 = new ApexPages.StandardController(prod);
            TENFORTYPREP pg206 = new TENFORTYPREP(sc206);
        
        Test.StopTest();
        
      }
      
   }