@isTest 
public class TestPractTaxExpert
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='PTEP_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        //Practical Tax Expert Editorial Content
        PageReference pageRef67 = Page.Res_Online_Prac_Tax; 
        
        Test.setCurrentPage(pageRef67);
        ApexPages.StandardController sc67 = new ApexPages.StandardController(prod);
        DisplayRESPRACTAX pg67 = new DisplayRESPRACTAX(sc67);
        
        Test.StopTest();
        
      }
      
   }