@isTest 
public class TestPassThrough
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='CCHSSPASSTHRU_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
         // Tax Compliance - Pass-Through Entities Self-Study Bundle 
            PageReference pageRef12 = Page.Tax_Comp_PassThru;
            
            Test.setCurrentPage(pageRef12);
            ApexPages.StandardController sc12 = new ApexPages.StandardController(prod);
            DisplayTaxCompPassThru pg12 = new DisplayTaxCompPassThru(sc12);
        
        Test.StopTest();
        
      }
      
   }