@isTest 
public class TestIntelliForms
 {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ATX-IF_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
            //Integrated Solutions - Interactive Forms
            PageReference pageRef22 = Page.IntSol_Inter_Forms; 
            
            Test.setCurrentPage(pageRef22);
            ApexPages.StandardController sc22 = new ApexPages.StandardController(prod);
            DisplayInterForms pg22 = new DisplayInterForms(sc22);
        
        Test.StopTest();
        
      }
      
   }