@isTest 
public class TestReform
 {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='HCR LIBRARY_2016';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2016',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
          //Books - Health Care Reform Library
            PageReference pageRef30 = Page.Res_Online_Library;
            
            Test.setCurrentPage(pageRef30);
            ApexPages.StandardController sc30 = new ApexPages.StandardController(prod);
            DisplayRESREFORM pg30 = new DisplayRESREFORM(sc30);
        
        Test.StopTest();
        
      }
      
   }