@isTest 
public class TestReturnRetrieval
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ATX-RETURN RETRIEVAL_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
            // Return Retrieval
            PageReference pageRef19 = Page.IntSol_Return_Retrieval;
            
            Test.setCurrentPage(pageRef19);
            ApexPages.StandardController sc19 = new ApexPages.StandardController(prod);
            DisplayIntSolRRetrieval pg19 = new DisplayIntSolRRetrieval(sc19);
        
        Test.StopTest();
        
      }
      
   }