@isTest 
public class TestMasterTax 
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ECBOOKMTG 17_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        //Books - U.S. Master Tax Guide (2016)
        PageReference pageRef46 = Page.Res_US_Master_Tax;
        
        Test.setCurrentPage(pageRef46);
        ApexPages.StandardController sc46 = new ApexPages.StandardController(prod);
        DisplayRESMASTERTAX pg46 = new DisplayRESMASTERTAX(sc46);
        
        Test.StopTest();
        
    }
    
 }