@isTest 
public class TestBookMA
 {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ECBOOKMATAX_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
             //Books - Massachusettes Taxes
            PageReference pageRef41 = Page.Res_State_Mass;
            
            Test.setCurrentPage(pageRef41);
            ApexPages.StandardController sc41 = new ApexPages.StandardController(prod);
            DisplayRESSTATEMASS pg41 = new DisplayRESSTATEMASS(sc41);
        
        Test.StopTest();
        
      }
      
   }