@isTest 
public class TestBookMI
 {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ECBOOKMITAX_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
            //Books - Michigan Taxes
            PageReference pageRef42 = Page.Res_State_Mich;
            
            Test.setCurrentPage(pageRef42);
            ApexPages.StandardController sc42 = new ApexPages.StandardController(prod);
            DisplayRESSTATEMICH pg42 = new DisplayRESSTATEMICH(sc42);
        
        Test.StopTest();
        
      }
      
   }