@isTest 
public class TestInternational
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='CCHSSINTLTAX_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        // Tax Compliance - U.S. International Taxation Self-Study Bundle 
            PageReference pageRef11 = Page.Tax_Comp_Intl;
            
            Test.setCurrentPage(pageRef11);
            ApexPages.StandardController sc11 = new ApexPages.StandardController(prod);
            DisplayTaxCompIntl pg11 = new DisplayTaxCompIntl(sc11);
        
        Test.StopTest();
        
      }
      
   }