@isTest 
public class TestGetWiseLV
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='TRGSEMGETWISELVREG_2016';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2016',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        //Books - Practical Tax Expert Editorial Content
            PageReference pageRef101 = Page.Get_Wise_LV;
            
            Test.setCurrentPage(pageRef101);
            ApexPages.StandardController sc101 = new ApexPages.StandardController(prod);
            DisplayGetWiseLV pg101 = new DisplayGetWiseLV(sc101);
        
        Test.StopTest();
        
      }
      
   }