@isTest 
public class TestToolkit
  {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='CLIENTLETTER_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
         //Books - Client Letter Toolkit
            PageReference pageRef27 = Page.Res_Online_Toolkit;
            
            Test.setCurrentPage(pageRef27); 
            ApexPages.StandardController sc27 = new ApexPages.StandardController(prod);
            DisplayRESTOOLKIT pg27 = new DisplayRESTOOLKIT(sc27);
        
        Test.StopTest();
        
      }
      
   }