@isTest 
public class TestOHCitites
 {
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ATX-OH CITIES_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
             //Integrated Solutions - Ohio Cities
            PageReference pageRef21 = Page.IntSol_Allo_Pack; 
            
            Test.setCurrentPage(pageRef21);
            ApexPages.StandardController sc21 = new ApexPages.StandardController(prod);
            DisplayIntSolAlloPack pg21 = new DisplayIntSolAlloPack(sc21);
        
        Test.StopTest();
        
      }
      
   }