@isTest 
public class TestEasyInterview
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='TWEASYINTERVIEW_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        //Easy Interview
        PageReference pageRef63 = Page.IntSol_Easy_Interview;
        
        Test.setCurrentPage(pageRef63);
        ApexPages.StandardController sc63 = new ApexPages.StandardController(prod);
        DisplayIntSolEzIntv pg63 = new DisplayIntSolEzIntv(sc63);
        
        Test.StopTest();
        
      }
      
   }