@isTest 
public class TestATXAdvantage
{
    static testMethod void AtxPackages() 
    {
        //Insert product 
        Product2 prod = new Product2();
        prod.Name = 'Laptop X200';
        prod.Family = 'Hardware';
        prod.Productcode='ATX-ADVANTAGE_2017';
        prod.IsActive=true;
        insert prod;
        
        //Insert PriceBook
        Pricebook2 priceBook= new Pricebook2();
        priceBook.Name='Custom Pricebook';
        priceBook.isActive=true ;
        insert priceBook;
        
       insert new Pricebook__c(Name = 'Pricebook2017',Pricebookid__c= priceBook.id);
        
        
        //Insert PriceBook Entry
        PricebookEntry priceBookEtry= new PricebookEntry();
        priceBookEtry.Pricebook2Id = priceBook.Id;
        priceBookEtry.Product2Id = prod.Id;
        priceBookEtry.UnitPrice = 12000; 
        priceBookEtry.IsActive = true;
        insert priceBookEtry;
        
        
        Test.StartTest();
        
        //ATX Advantage
        PageReference pageRef56 = Page.Test_ATX_Advantage_Page;
        
        Test.setCurrentPage(pageRef56);
        ApexPages.StandardController sc56 = new ApexPages.StandardController(prod);
        DisplayATXADV pg56 = new DisplayATXADV(sc56);
        
        Test.StopTest();
        
      }
      
   }