/**********************************************************************
Name: TestbfInsUpdContact
Copyright © 2012 WK
======================================================
======================================================
Purpose: This test class is to do test coverage for the Trigger "bfInsUpdContact" 
======================================================
======================================================
History
-----------------------------------------------------------------------
VERSION   AUTHOR   DATE       DETAIL 
1.0       Natesh   28/08/2012 INITIAL DEVELOPMENT
***********************************************************************/
@isTest
private class TestbfInsUpdContact {
    static testMethod void myUnitTest() {
        //Create Contacts
        /*  Commented as Associated Triggers are INACTIVE  
        Id AMFSNSRecordTypeId=[SELECT Id FROM RecordType WHERE Name='AM/FS/NS Contact'].Id;
        Contact contactItem = new Contact(LastName='Test Contact 1', Phone='1122222222', Fax='1122222222', RecordTypeId=AMFSNSRecordTypeId);
        insert contactItem;
        */
    }
}